service: pdlbrd-repository-api

provider:
  resourceGroup: wabrez-westus-dev-paddleboard
  prefix: ${opt:prefix, 'sls'}
  name: azure
  region: West US
  runtime: nodejs10.x
  environment:
    COSMOS_ENDPOINT: ${env:COSMOS_ENDPOINT}
    COSMOS_KEY: ${env:COSMOS_KEY}
  apim:
    name: wabrez-wus-dev-pdlbrd-apim
    apis:
      - name: repository-api
        subscriptionRequired: false
        displayName: Repository API
        description: Repository CRUD REST API
        protocols:
          - https
        path: repositories
        authorization: none
      - name: user-profile-api
        subscriptionRequired: false
        displayName: User Profile API
        description: User Profile CRUD REST API
        protocols:
          - https
        path: users
        authorization: none
    backends:
      - name: repository-backend
        url: api/repositories
      - name: user-profile-repository-backend
        url: api/users
    cors:
      allowCredentials: false
      allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      allowedHeaders:
        - "*"
      exposeHeaders:
        - "*"

plugins:
  - serverless-azure-functions
  - serverless-webpack

functions:
  # Repositories
  getRepositoryListByUser:
    handler: src/handlers/repository.getRepositoryListByUser
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: users/{userId}/repositories
          authLevel: anonymous
    apim:
      api: user-profile-api
      backend: user-profile-repository-backend
      operations:
        - method: GET
          urlTemplate: /{userId}/repositories
          templateParameters:
            - name: userId
              type: string

  getRepository:
    handler: src/handlers/repository.getRepository
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: users/{userId}/repositories/{repositoryId}
          authLevel: anonymous
    apim:
      api: user-profile-api
      backend: user-profile-repository-backend
      operations:
        - method: GET
          urlTemplate: /{userId}/repositories/{repositoryId}
          templateParameters:
            - name: userId
              type: string
            - name: repositoryId
              type: string

  postRepository:
    handler: src/handlers/repository.postRepository
    events:
      - http: true
        x-azure-settings:
          methods:
            - POST
          route: users/{userId}/repositories
          authLevel: anonymous
    apim:
      api: repository-api
      backend: repository-backend
      operations:
        - method: POST
          urlTemplate: /{userId}/repositories

  putRepository:
    handler: src/handlers/repository.putRepository
    events:
      - http: true
        x-azure-settings:
          methods:
            - PUT
          route: users/{userId}/repositories/{repositoryId}
          authLevel: anonymous
    apim:
      api: repository-api
      backend: repository-backend
      operations:
        - method: PUT
          urlTemplate: /{userId}/repositories/{repositoryId}
          templateParameters:
            - name: repositoryId
              type: string

  patchRepository:
    handler: src/handlers/repository.patchRepository
    events:
      - http: true
        x-azure-settings:
          methods:
            - PATCH
          route: users/{userId}/repositories/{repositoryId}
          authLevel: anonymous
    apim:
      api: repository-api
      backend: repository-backend
      operations:
        - method: PATCH
          urlTemplate: /{userId}/repositories/{repositoryId}
          templateParameters:
            - name: repositoryId
              type: string

  deleteRepository:
    handler: src/handlers/repository.deleteRepository
    events:
      - http: true
        x-azure-settings:
          methods:
            - DELETE
          route: users/{userId}/repositories/{repositoryId}
          authLevel: anonymous
    apim:
      api: repository-api
      backend: repository-backend
      operations:
        - method: DELETE
          urlTemplate: /{userId}/repositories/{repositoryId}
          templateParameters:
            - name: repositoryId
              type: string
